include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - require_trailing_commas
    - unawaited_futures
    - use_build_context_synchronously
    - directives_ordering
